language: python
python:
    - "3.6"
before_install:
    - pip install --upgrade pytest
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest --cov=./
env:
    - CODECOV_TOKEN=25ed5e48-9d35-4f2e-901e-f43647327ff3
after_success:
    - codecov
